name: Linux
on: [push, pull_request]
env:
        BUILD_TYPE: Release

jobs:
        build:
                name: ${{ matrix.config.name }}
                runs-on: ${{ matrix.config.os }}
                strategy:
                        fail-fast: false
                        matrix:
                                config:
                                        - {
                                                name: "Ubuntu Latest GCC", artifact: "Linux.7z",
                                                os: ubuntu-latest,
                                                cc: "gcc", cxx: "g++"
                                          }
                steps:
                        - uses: actions/checkout@v1
                        - name: Print env
                          run: |
                                echo github.event.action: ${{ github.event.action }}
                                echo github.event_name: ${{ github.event_name }}
                        - name: Installing dependencies for Ubuntu Linux
                          run: |
                                sudo apt-get update -y
                                sudo add-apt-repository ppa:ubuntu-toolchain-r/test
                                sudo apt install cmake curl -y
                                sudo apt install gcc-9 g++-9
                                echo -e "\nGCC VERSION:\n"
                                gcc --version
                                echo -e "\nCMake VERSION:\n"
                                cmake --version
                        - name: Configuring and Build
                          shell: bash
                          run: |
                                BUILD_AND_TEST_SCRIPT="makeprg_build.sh"
                                TEST_SCRIPT="run_test.sh"
                                chmod +x ./${BUILD_AND_TEST_SCRIPT}
                                chmod +x ./${TEST_SCRIPT}
                                ./${BUILD_AND_TEST_SCRIPT}
